### PR TITLE
Update changelog for release 2.0.1

### PR DESCRIPTION
**Pull request by fkang-pu**
## Summary Change Description

Added DataFrame changes to changelog before creating tag for release 2.0.1.

## Affected Issue Numbers

None

### CODE REVIEW

**Review by hepcat72 — APPROVED** [review]
This might be a good opportunity to fix the missing closing `div` tag I noted in your previous PR.

https://github.com/Princeton-LSI-ResearchComputing/tracebase/pull/595#discussion_r1060790278

**Review by lparsons — APPROVED** [review]
The change to the HTML uses a different class, and looks a bit cleaner, at least to my eye.

Nice addition to the changelog too.

**Comment by fkang-pu** [comment]
> This might be a good opportunity to fix the missing closing `div` tag I noted in your previous PR.
> 
> [#595 (comment)](https://github.com/Princeton-LSI-ResearchComputing/tracebase/pull/595#discussion_r1060790278)

@hepcat72 Thank you so much for your suggestions about PR 595. Sorry I didn't reply sooner, somehow I didn't get email notifications about your comments (maybe it's due to that the PR was closed before your review). I made changes to `customtags.py` using the 2nd set of code you suggested,  but it seems to me I still need to use `mark_safe `to get correct display.

**Review by hepcat72 — APPROVED** [review]

**Comment by fkang-pu** [comment]
@lparsons I meant to request new review from Rob, but probably sent to all of you. I know you just reviewed, please ignore my new request.

**Review by hepcat72 — APPROVED** [review]

**Pull request merged**
