### PR TITLE
Merge migration scripts

### PR DESCRIPTION
**Pull request by lparsons**
## Summary Change Description

Merging the migration scripts for a couple of PRs to clean things up.
This may require that developers re-create their database prior to
running migrations (thus not something we'd want to do in production).

Moved the max tracer_labeled_count to a constant.

Step to generate the new migration scripts:
```
rm DataRepo/migrations/0002*
rm DataRepo/migrations/0003*
rm DataRepo/migrations/0004*
python manage.py makemigrations
```

## Code Review Notes

Merging migrations isn't required, but I wanted to try it out to see how things worked. If we accept these changes, then developers may need to recreate their database:

```
sudo -u postgres psql
drop database tracebase;
create database tracebase;
\q
python manage.py migrate
```

## Checklist

- [x] All issue requirements satisfied (or no linked issues)
- [x] [Linting passes](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#linting).
- [x] [Migrations created & committed *(or no model changes)*](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#migration-process)
- [x] [Tests implemented *(or no code changes)*](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#test-implementation)
- [x] [All tests pass](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#quality-control)

### CODE REVIEW

**Review by hepcat72 — APPROVED** [review]
Could you share the manage.py commands you used for the migration changes?  Thanks for documenting the DB update process.

**Comment by lparsons** [comment]
> Could you share the manage.py commands you used for the migration changes? Thanks for documenting the DB update process.

Sorry, should have included that. I added them to the PR description.

**Review by jcmatese — APPROVED** [review]
Fine by my.  Still wonder about having migrations in the repo, given this issue/PR, but perhaps this issue will settle down given more collective Django experience, and fewer massive model changes (making migrations more useable/useful, fewer possibility for conflicts, etc.).

**Comment by lparsons** [comment]
This issue is exactly why I do want migrations in the repo.

This solution makes some versions of the code in the main branch unable to be upgraded to the current version. That's not something we'll want later on, but for now is totally acceptable. Later, however, we may want some custom code in the migrations to handle a particularly tricky case (like this). If that happens, the custom code will have to be in the repo.

**Pull request merged**
