### PR TITLE
Revised how dataframes are stored for efficiency

### PR DESCRIPTION
**Pull request by hepcat72**
## Summary Change Description

I realized that a number of methods were converting back and forth between dataframes and dicts and I realized that it would all be much easier if I save the production of actual dataframes until after the samples (etc) have been added.

So I converted all instances of `dfs_dict` from a `dict of pandas dataframes` to a `dict of pandas' style dicts`, e.g. `{"columnname": {0: "row 1 value", 1: "row 2 value"}}`.

This prevents the necessity of various methods converting back and forth between dataframes and dicts.  It also addresses issues of places where I was temporarily using lists instead of pandas' version of lists (dicts keyed by sequential integeras starting from 0).

## Affected Issues/Pull Requests

- Resolves no issue, but related to #829
- Merges into PR #930
- Next PR: #932

## Review Notes

See comments in-line.

## Checklist

This pull request will be merged once the following requirements are met.  The
author and/or reviewers should uncheck any unmet requirements:

- Review requirements
  - Minimum approvals: 1 
  - No changes requested
  - All blocking issues resolved by reviewers
  - Specific reviewers: @__add_username_here__
    
  - Review period: 2 days 
- Associated issue/pull request requirements:
  
  - [x] All requirements in affected issues marked "resolved" are satisfied
  - [x] All required pull requests are merged *(or none)*
- Basic requirements
  
  - [x] [All linters pass](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#linting)
  - [x] [All tests pass](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#quality-control)
  - [x] All conflicts resolved
- Overhead requirements
  
  - [x] [New/changed method tests implemented/updated *(or no change)*](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#test-implementation)
  - [ ] [Updated *Unreleased* section of `changelog.md` *(or no change)*](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/changelog.md)
  - [x] [Migrations created & committed *(or no change)*](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#migration-process)

### CODE REVIEW

**Review by lparsons — APPROVED** [review]
This does seem to remove some calls to `to_dict()` though it's not clear to me why things were DataFrames in the first place and what functionality was gained/lost.

One downside is that many of the function names are now rather misleading and the data structure is less well defined. `DataFrame` was easy to check for and understand how to use, but the structure now is less easy to ensure it's correct.

**Comment by lparsons** [comment]
Also, it's not clear why this is stacked on top of the `all_missing_treatments_exception` branch and not merging directly into `main`. It seems tangential, but not a blocking issue.

**Comment by hepcat72** [comment]
Sorry, I forgot and already merged.  Too many concurrent conversations, lol.  I suspect they're all changed. 🤞🏻

**Comment by hepcat72** [comment]
Ok. *phew*  They *are* changed... with one caveat: I intentionally left `get_dataframe_template()`.  My thinking was that they are a template *for* a dataframe, which explains their structure (using dict keys that are sequential integers).  If you don't use integers, they don't play well with excel files that are read into dataframes (and dicts).

**Pull request merged**
