### PR TITLE
add 3 views and templates to test web page rendering speed

### PR DESCRIPTION
**Pull request by fkang-pu**
## Summary Change Description

I am not asking for a formal review, just want to share a few test cases for displaying peak data for a study.

- function based view "selected_data":

  page title: "Selected Data"
url: http://127.0.0.1:8000/DataRepo/selected_data/
notes: 
filter and display peak data  for a study (imitating Rob's basic search page)
used "select_related" for queryset,  instead of "prefetch_related"
template: selected_data_list.html
SQL query used join and subquery, should be fast
web content rendering was very slow (slower than Rob's basic search page)

- function based view "selected_t1":
  tried to demonstrate that the slowness was not due to displaying calculated values

  page title: ""Selected Data --test 1"
url: http://127.0.0.1:8000/DataRepo/selected_t1/
notes: 
The view is more or less the same as "selected_data" 
template: selected_data_t1.html (omitted the fields for calculated values based on functions)
web content rendering was as slow as "Selected Data"

- function based view "selected_t2":

  page title: "Selected Data -- test2 using values()"
url: http://127.0.0.1:8000/DataRepo/selected_t2/
The subquery is the same as used for "selected_data" and "selected_t1"
The queryset for peakdata used "values() " and defined field list
template: selected_data_t2.html  
web content rendering was very fast
Big issue: I don't know how to retrieve and display calculated values (e.g. fraction) using values().

## Code Review Notes

- Both "selected_data" and "selected_t1" were slow - with or without displaying values based on functions (e.g. fraction)
- "selected_t2" was fast, but I don't know how to handle the values based on functions (e.g. fraction)

## Checklist

- [ ] All issue requirements satisfied (or no linked issues)
- [ ] [Linting passes](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#linting).
- [ ] [Migrations created & committed *(or no model changes)*](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#migration-process)
- [ ] [Tests implemented *(or no code changes)*](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#test-implementation)
- [ ] [All tests pass](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#quality-control)

### CODE REVIEW

**Comment by hepcat72** [comment]
I tried checking out this branch to test it, but could not get it to work.  I get errors on those pages.

**Comment by fkang-pu** [comment]
I think the model updated after I created this PR, I also got error in my local branch (column DataRepo_peakgroup.ms_run_id does not exist...). I will take a look.

**Comment by fkang-pu** [comment]
@hepcat72 I rebased my local branch and made a commit for replacing ms_run with msrun. It worked locally for me. Just pushed the commit to GitHub.

**Comment by hepcat72** [comment]
I'm going to close this @fkang-pu. We have the branch: `fk_queryset_t1` and can all access it whether or not the PR exists.  Feel free to reopen, if you wish to have it reviewed and merged into main.

**Pull request closed without merging**
