### PR TITLE
Superlinter black update

### PR DESCRIPTION
**Pull request by lparsons**
## Summary Change Description

Update SuperLinter to version 6. See list of significant changes here: https://github.com/super-linter/super-linter/blob/main/docs/upgrade-guide.md

In addition to changing the super-linter version, this required the following:
* Add specific permissions to GitHub actions to restrict the permissions granted to `GITHUB_TOKEN`
* Some formatting changes dictated by updated versions of black, flake8, etc.
* One actual code change required was replacing direct comparisons of `type()` with the use of `isintance()`. See https://www.flake8rules.com/rules/E721.html.

## Checklist

This pull request will be merged once the following requirements are met.  The
author and/or reviewers should uncheck any unmet requirements:

- Review requirements
  - Minimum approvals: 1 
  - No changes requested
  - All blocking issues resolved by reviewers
  - Specific reviewers: @__add_username_here__
    
  - Review period: 2 days 
- Associated issue/pull request requirements:
  
  - [x] All requirements in affected issues marked "resolved" are satisfied
  - [x] All required pull requests are merged *(or none)*
- Basic requirements
  
  - [x] [All linters pass](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#linting)
  - [x] [All tests pass](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#quality-control)
  - [x] All conflicts resolved
- Overhead requirements
  
  - [x] [New/changed method tests implemented/updated *(or no change)*](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#test-implementation)
  - [ ] [Updated *Unreleased* section of `changelog.md` *(or no change)*](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/changelog.md)
  - [x] [Migrations created & committed *(or no change)*](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#migration-process)

### CODE REVIEW

**Review by hepcat72 — APPROVED** [review]
Looks like the new black(/linters) made some healthy changes, but I'm curious about the process for the github yaml file updates.  Did you make changes based on trial and error (and googling error messages) or did you follow some superlinter documentation?  I see you added comments with links relating to some changes, so possibly a mix?  If there were any other resources used, perhaps a comment at the top, documenting it would be useful.  If not, then that's some insightful debugging.

**Comment by hepcat72** [comment]
Ah, the guide linked in the description of the PR - that would be good to add to the yaml(s).

**Comment by lparsons** [comment]
> Looks like the new black(/linters) made some healthy changes, but I'm curious about the process for the github yaml file updates. Did you make changes based on trial and error (and googling error messages) or did you follow some superlinter documentation? I see you added comments with links relating to some changes, so possibly a mix? If there were any other resources used, perhaps a comment at the top, documenting it would be useful. If not, then that's some insightful debugging.

I used the YAML provided in the README at https://github.com/super-linter/super-linter as a guide for most of the changes. Then got an error from the `CHECKOV` linter warning me about the top-level permissions for GitHub actions, so I added that.

> Ah, the guide linked in the description of the PR - that would be good to add to the yaml(s).

We can, though it only seems relevant during the transition period to me. I didn't actually read or use that, tbh, just pointing others to it in case they found it useful.

**Comment by lparsons** [comment]
@fkang-pu and @jcmatese No need for a "review" of this PR, but wanted to make sure you were both aware before we merge this. It updates super-linter and some of the linter versions in the `dev/requirements.txt` to newer versions to match. Just in case you need / want to update anything in your own dev environments. Give a thumbs up here and we'll merge.

**Review by jcmatese — APPROVED** [review]

**Comment by lparsons** [comment]
@fkang-pu just pinging you to make sure you've seen this before we merge it. Can you thumb up or approve the PR to confirm? If you need more time, just let us know.

**Review by fkang-pu — APPROVED** [review]
The changes look good to me. It's nice to use `isinstance` to check object type. I reviewed a part of this PR two days ago, but forgot to continue after taking care of RT ticket. Sorry about the delay.

**Pull request merged**
