### PR TITLE
Suppress errors about missing peak annotation files during study-doc only validation

### LINKED ISSUE #1169: Suppress errors about missing files when processing the `Peak Annotation Files` sheet
### Inspiration

Since the validate page only accepts the Study doc, the peak annotation files are not available for processing and thus errors are buffered about missing files.  This is expected behavior, however the errors are not necessary when just validating the Study doc by itself.

### Description

Implement a way to either skip the load of the peak annotation files from the `Peak Annotation Files` sheet, or retroactively remove the buffered errors about the missing files.

Test with: [MASTER STUDY DOC FOR TRACEBASE_exp011b3_240816.xlsx](https://github.com/user-attachments/files/16662101/MASTER.STUDY.DOC.FOR.TRACEBASE_exp011b3_240816.xlsx)

### Alternatives

None

### Dependencies

None

### Comment

None

-----

### Assumptions

1. List of assumptions that the code will not explicitly address/check
2. E.g. We will assume input is correct (explaining why there is no validation)

### Limitations

1. A list of things this work will specifically not do
2. E.g. This feature will only handle the most frequent use case X

### Affected Components

- change: File path or DB table ...
- add: Environment variable or server setting
- delete: External executable or cron job

### Requirements

- [ ] 1. List of numbered conditions to be met for the feature
- [ ] 2. E.g. Every column/row must display a value, i.e. cannot be empty
- [ ] 3. Numbers for reference & checkboxes for progress tracking

#### Interface Change description

None provided

#### Code Change Description

None provided

#### Tests

- [ ] 1. A description of at least one test for each requirement above.
- [ ] 2. E.g. Test for req 2 that there's an exception when display value is ''
- [ ] 3. Numbers for reference & checkboxes for progress tracking

### PR DESCRIPTION
**Pull request by hepcat72**
## Summary Change Description

Suppressed errors about missing peak annotation files when validating only the study doc.

You can test with [MASTER STUDY DOC FOR TRACEBASE_exp011b3_240816.xlsx](https://github.com/user-attachments/files/16662101/MASTER.STUDY.DOC.FOR.TRACEBASE_exp011b3_240816.xlsx).  It produces lots of errors, but `FileFromInputNotFound` is no longer one of them.

## Affected Issues/Pull Requests

- Resolves #1169
- Merges into main

## Review Notes

See comments in-line.

## Checklist

This pull request will be merged once the following requirements are met.  The
author and/or reviewers should uncheck any unmet requirements:

- Review requirements
  - Minimum approvals: 1 
  - No changes requested
  - All blocking issues resolved by reviewers
  - Specific reviewers: @__add_username_here__
    
  - Review period: 2 days 
- Associated issue/pull request requirements:
  
  - [x] All requirements in affected issues marked "resolved" are satisfied
  - [x] All required pull requests are merged *(or none)*
- Basic requirements
  
  - [x] [All linters pass](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#linting)
  - [x] [All tests pass](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#quality-control)
  - [x] All conflicts resolved
- Overhead requirements
  
  - [x] [New/changed method tests implemented/updated *(or no change)*](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#test-implementation)
  - [ ] [Updated *Unreleased* section of `changelog.md` *(or no change)*](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/changelog.md)
  - [x] [Migrations created & committed *(or no change)*](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#migration-process)

### CODE REVIEW

**Comment by jcmatese** [comment]
I am OK with this, but why would you want to suppress this error?  Should all studies have at least 1 peak file?   Is this only in the second step of study validation, as opposed to submission (even though the edits are in `submission.py`)?

**Comment by jcmatese** [comment]
> I am OK with this, but why would you want to suppress this error? Should all studies have at least 1 peak file? Is this only in the second step of study validation, as opposed to submission (even though the edits are in `submission.py`)?

And by "submission", and am thinking about loading...

**Comment by hepcat72** [comment]
> I am OK with this, but why would you want to suppress this error? Should all studies have at least 1 peak file? Is this only in the second step of study validation, as opposed to submission (even though the edits are in `submission.py`)?

From the linked issue:

> Since the validate page only accepts the Study doc, the peak annotation files are not available for processing and thus errors are buffered about missing files. This is expected behavior, however the errors are not necessary when just validating the Study doc by itself.

**Comment by hepcat72** [comment]
Thanks for the review @jcmatese!

**Pull request merged**
