### PR TITLE
Labeled count clarifications

### LINKED ISSUE #40: Add help text to define scope of label count
### Feature Inspiration

Didn't understand what defined the scope of label count or what precisely was being counted.  And the existing help text for PeakData.labeled_count field is confusing: "the M+ value (i.e. Label) for this observation.  '1' means one atom is labeled.  '3' means 3 atoms are labeled".

### Feature Description

Wherever a label count is an item in a class in a model, add help text defining the counting scope.  Two examples where clarification could be useful to the unfamiliar:

https://github.com/Princeton-LSI-ResearchComputing/tracebase/pull/37/files#r614953889

What's the context of TracerLabeledClass.MAX_LABELED_COUNT? Is it the max number of labels that can occur together in a sample? It must not be since there are only 5 choices. Perhaps the number of labeled (e.g.) carbons in a molecule? What's the purpose of having a max?

https://github.com/Princeton-LSI-ResearchComputing/tracebase/pull/37/files#r614953889

I think maybe help text for this field [Animal.tracer_labeled_count] might be useful. Maybe not for those experienced with the data, but perhaps for new undergrads and people like me.

### Alternatives Considered

A definitions page or reference to existing documentation that would explain things.

### Comment

https://github.com/Princeton-LSI-ResearchComputing/tracebase/pull/37/files#r615011427

-----

### Assumptions

none

### Requirements

- The meaning of existing labeled_count field help text is easy to understand
- Variable names regarding labeled_count values provide the counting scope in their name
- Any field defined for labeled_count in any table has help text

### Limitations

- This isn't for help text other than to clarify instances of labeled_count

### Affected/Changed Components

- DataRepo/models.py

#### GUI Change description

Help text associated with database fields.

#### Code Change Description *(Pseudocode optional)*

- Change `MAX_LABELED_COUNT` to something conveying scope.
- Add help text to `Animal.tracer_labeled_count`
- Clarify `PeakData.labeled_count`

#### Tests

Just string changes. No tests necessary.

### PR DESCRIPTION
**Pull request by hepcat72**
## Summary Change Description

Added help test to animal.tracer_labeled_count.
Renamed MAX_LABEL_COUNT to MAX_LABELED_ATOMS.
Re-worded PeakData.labeled_count help text.

## Affected Issue Numbers

- Resolves #40

Note, I mainly took this issue because I need my other PR merged before I can really take the other view issues I plan to take.

## Code Review Notes

The change to `MAX_LABELED_ATOMS` is intended to imply the scope of a "compound".  I.e. the maximum is applied to atoms in a compound as opposed to labeled compounds given to an animal.

As I understand the paper, an animal is given a labeled compound with a specific number of labeled atoms (Animal.tracer_labeled_count).  The animal breaks down that compound or includes components of it in other synthesis mechanisms - and those labeled compounds are detected in the mass spec observations.  So I felt it was important to be able to distinguish those scopes in the help text of the 2 labeled_count fields.

## Checklist

- [x] All issue requirements satisfied (or no linked issues)
- [x] [Linting passes](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#linting).
- [x] [Migrations created & committed *(or no model changes)*](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#migration-process)
- [x] [Tests implemented *(or no code changes)*](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#test-implementation)
- [x] [All tests pass](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#quality-control)

### CODE REVIEW

**Comment by hepcat72** [comment]
Not sure why my local run of superlinter didn't complain about not having made migrations.

**Comment by lparsons** [comment]
> Not sure why my local run of superlinter didn't complain about not having made migrations.

Super Linter only runs the linters. The rest of the GitHub actions are in a separate workflow.

**Review by lparsons — APPROVED** [review]
Nice, make things clearer.

Obviously, needs to be cleaned up to pass linting and tests.

**Comment by hepcat72** [comment]
> Nice, make things clearer.
> 
> Obviously, needs to be cleaned up to pass linting and tests.

What the heck. Oh, was it the migrations?  Must be. I ran that after superlinter. Ugh.

**Comment by hepcat72** [comment]
It's such a pet peeve of mine when the manual linter run doesn't match the superlinter run...

```
# superlinter...
2021-05-04 14:06:49 [INFO]   File:[/tmp/lint/DataRepo/migrations/0006_auto_20210503_1855.py]
2021-05-04 14:06:49 [ERROR]   Found errors in [flake8] linter!
2021-05-04 14:06:49 [ERROR]   Error code: 1. Command output:
------
/tmp/lint/DataRepo/migrations/0006_auto_20210503_1855.py:32:121: E501 line too long (135 > 120 characters)
------
# Manual runs:
(tracebase/.venv) gen-rl-macbookair[2021-05-04 10:11:10]:...~/PROJECT-local/TRACEBASE/REPO/TraceBase$ flake8 . --config .flake8
(tracebase/.venv) gen-rl-macbookair[2021-05-04 10:11:35]:...~/PROJECT-local/TRACEBASE/REPO/TraceBase$ flake8 .
(tracebase/.venv) gen-rl-macbookair[2021-05-04 10:12:15]:...~/PROJECT-local/TRACEBASE/REPO/TraceBase$ flake8 DataRepo/migrations/0006_auto_20210503_1855.py
DataRepo/migrations/0006_auto_20210503_1855.py:32:121: E501 line too long (135 > 120 characters)
```
`.flake8` seems to be set to ignore migrations, yet superlinter checks it:
```
(tracebase/.venv) gen-rl-macbookair[2021-05-04 10:09:46]:...~/PROJECT-local/TRACEBASE/REPO/TraceBase$ more .flake8 
[flake8]
max-line-length = 120
ignore =
    E231  # There should be whitespace after the characters ,, ;, and :. black; fixed in black 20 (https://github.com/psf/black/issues/1289)
exclude = .venv,__pycache__,migrations
```
So I removed migrations from `.flake8` and now it matches:
```
(tracebase/.venv) gen-rl-macbookair[2021-05-04 10:15:48]:...~/PROJECT-local/TRACEBASE/REPO/TraceBase$ flake8 .
./DataRepo/migrations/0006_auto_20210503_1855.py:32:121: E501 line too long (135 > 120 characters)
```
I think we're leaning toward ignoring migrations in linting, but officially it's included.  I suspect superlinter is running flake8 on every file explicitly (like I did above), so I think adding `migrations` to `.flake8` doesn't do anything.  I am going to push the change to remove migrations so that running it manually matches superlinter.

**Review by lparsons — APPROVED** [review]

**Review by jcmatese — APPROVED** [review]

**Review by fkang-pu — APPROVED** [review]

**Pull request merged**
