### PR TITLE
v2.0.4 release branch

### PR DESCRIPTION
**Pull request by hepcat72**
For details, see #743 (which is closed because I implemented it on the wrong branch (main).

### CODE REVIEW

**Comment by hepcat72** [comment]
I'm pretty sure I did this wrong, but I was not clear at all what the "right" way is...  I created a branch "v2.0.3" from the tag of the same name, then created a branch "v2.0.4" off that branch, and copied over my changes, then created a PR from that, merging into branch v2.0.3.  Then I plan to create the release using that v2.0.4 branch? That seems really circuitous. How is this *supposed* to be done?

**Comment by lparsons** [comment]
One option would be to create a branch `release-v2.0.x` starting at the tagged revision. Merge this fix into that branch when the fix is ready. Then create a tag `v2.0.4` on the `release-v2.0.x` branch with the fix. Then, from `main`, merge in `release-2.0.x`. 

I believe this is similar to how the galaxy project does things. Tags are single points in time, branches can "grow", meaning we can add more commits to them.

**Comment by hepcat72** [comment]
This is the re-made PR for #743, but it merges into the release branch I created called [release_2.0.x](https://github.com/Princeton-LSI-ResearchComputing/tracebase/tree/release_2.0.x).

**Review by lparsons — APPROVED** [review]
LGTM

**Pull request merged**
