### PR TITLE
Migrations documentation and PR additions

### PR DESCRIPTION
**Pull request by hepcat72**
# Summary Change Description

Made additions to try to avoid missing making migrations.

## Affected Issue Numbers

none

## Code Review Notes

- **NOTE, THIS PR IS A BRANCH OFF OF THE BRANCH FOR PR #24 (`msrun_protocol`)! (I changed the base branch so that you see the diff with msrun_protocol for review.)**
- I removed the `---`-delimited section at the top of the PR template because github does not remove it for submitters like it does for the issue templates.  But I left in a single `---` at the top to prevent markdownlint from throwing an MD041 error in the template (top level heading missing).
- I also tweaked the wordings in the checklist so there's never an `n/a` case.
- It's also notable that if you have any text past a link on a line (where the link characters make the line longer than 80 characters), it will throw an error.  But if the last thing on a line is a link that puts the characters past 80, there is no error.  However, it doesn't know what a link is.  It just applies a brain-dead rule about a length of non-whitespace characters going over 80.

## Checklist

- [x] All (linked above) issue requirements satisfied
- [x] [Linting passes](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#linting).
- [x] [Tests implemented](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#test-implementation)
- [x] [All tests pass](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#quality-control)

### CODE REVIEW

**Comment by hepcat72** [comment]
Oh geez.  The `---` generates an MD041 error now.  I swear it didn't before.  Maybe I didn't save.  I guess I'll have to change the `##`s to `#`.

**Review by jcmatese — APPROVED** [review]

**Review by lparsons — APPROVED** [review]
LGTM. One comment:

> Oh geez. The `---` generates an MD041 error now. I swear it didn't before. Maybe I didn't save. I guess I'll have to change the `##`s to `#`.

This is fine as is, but I'd also be fine skipping the linting on the `.github` dir. The level 1 headings are huge. :wink:

**Comment by hepcat72** [comment]
[I agree](https://github.com/DavidAnson/markdownlint/issues/380).

**Comment by hepcat72** [comment]
I manually changed the h1 in this PR.  The difference is less than I'd recalled.

**Comment by hepcat72** [comment]
> LGTM. One comment:
> 
> > Oh geez. The `---` generates an MD041 error now. I swear it didn't before. Maybe I didn't save. I guess I'll have to change the `##`s to `#`.
> 
> This is fine as is, but I'd also be fine skipping the linting on the `.github` dir. The level 1 headings are huge. 😉

Actually, I'd added `.github` to the `markdownlint` check routine because superlinter in the github action was checking those files by default and throwing errors.  But now that you've added the `FILTER_REGEX_EXCLUDE` to `.github/workflows/superlinter.yml`, maybe I can add .github to it?  Do you think that would have any unwanted side-effects @lparsons?

**Review by fkang-pu — APPROVED** [review]

**Comment by hepcat72** [comment]
> > LGTM. One comment:
> > > Oh geez. The `---` generates an MD041 error now. I swear it didn't before. Maybe I didn't save. I guess I'll have to change the `##`s to `#`.
> > 
> > 
> > This is fine as is, but I'd also be fine skipping the linting on the `.github` dir. The level 1 headings are huge. 😉
> 
> Actually, I'd added `.github` to the `markdownlint` check routine because superlinter in the github action was checking those files by default and throwing errors. But now that you've added the `FILTER_REGEX_EXCLUDE`s to `.github/workflows/superlinter.yml`, maybe I can add `.github` to it? Do you think that would have any unwanted side-effects @lparsons?

OK, that worked.  I added .github to the FILTER_REGEX_EXCLUDE setting in the superlinter config, eliminated my markdownlint work-arounds, and removed `.github` from the CONTRIBUTING doc and everything passes.

So I'll merge this once msrun_protocol is ready to merge.

**Pull request merged**
