### PR TITLE
Atomic transactions added to new loaders

### PR DESCRIPTION
**Pull request by hepcat72**
## Summary Change Description

This implements the atomic transaction TODO item in the sequence load PR series.  This resolves an unrealized concern about the nature of the `AggregatedErrors` strategy, where exceptions are allowed to happen and processing of an input file is allowed to continue despite those exceptions (which are buffered and the code is allowed to proceed).

In a discussion I had on the django forum about a different but related issue, I realized that I had been mis-interpreting what I would consider ambiguous language in the django docs about what to do in the event of database-related exceptions.  I had interpreted the language about catching and rolling back in another try/except block to be referring to an *outer* block, when allowing the code to proceed, making things safe.  But I learned that what it meant to convey (implicitly) was that an *inner* try/except block should be used to roll back *just* the record that caused the exception, and once I realized that, it made total sense to me that that's how `AggregatedErrors` should have been used:

1. Catch inside the atomic block (and inside the loop iterating over the input) to buffer the exception
2. Then immediately *raise* the exception inside that inner atomic block and inside the loop
3. Then *catch* the exception *outside* the atomic block, so that the failed record gets rolled back (but still inside the loop) and ignore the exception to continue iterating

The basic design pattern I implemented in this change is:

```
def load_data(self):
    for row in df.iterrows:
        try:
            self.get_or_create_mymodel_rec(row)
        except Exception:
            pass

@transaction.atomic
def get_or_create_mymodel_rec(self, row):
    try:
        rec_dict = self.create_rec_dict(row)
        Model.objects.get_or_create(**rec_dict)
    except Exception as e:
        self.handle_exception(e, MyModel, rec_dict)  # This buffers the exception
        raise e
    return rec
```

Note, the only place where I had already implemented this design pattern was in the sequences loader, but that code had a couple mistakes and I also streamlined it a bit.

There are a couple other trivial changes, like typo fixes and linting.  Incidentally, the linting fixes were fixed in 2 branches (by mistake, due to retroactively splitting the TODO items into 2 PRs somewhat retroactively) and I will address those conflicts on merge.

Oh, and this also removes the **unused `STUDY_CODE`** references, due to concerns expressed over that strategy during a prior review.  I will implement that if/when I get around to it.

## Affected Issues/Pull Requests

- Resolves TODO item left during the sequence load PR series
- Merges into #883

## Review Notes

See comments in-line.

## Checklist

This pull request will be merged once the following requirements are met.  The
author and/or reviewers should uncheck any unmet requirements:

- Review requirements
  - Minimum approvals: 1 
  - No changes requested
  - All blocking issues resolved by reviewers
  - Specific reviewers: @__add_username_here__
    
  - Review period: 2 days 
- Associated issue/pull request requirements:
  
  - [x] All requirements in affected issues marked "resolved" are satisfied
  - [x] All required pull requests are merged *(or none)*
- Basic requirements
  
  - [x] [All linters pass](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#linting)
  - [x] [All tests pass](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#quality-control)
  - [x] All conflicts resolved
- Overhead requirements
  
  - [x] [New/changed method tests implemented/updated *(or no change)*](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#test-implementation)
  - [ ] [Updated *Unreleased* section of `changelog.md` *(or no change)*](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/changelog.md)
  - [x] [Migrations created & committed *(or no change)*](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#migration-process)

### CODE REVIEW

**Comment by jcmatese** [comment]
I think this _might_ warrant some discussion about the overall strategy, because rolling back file-based transactions might require different strategies in different contexts.  For find-or-create loaders, row-based transactions are _probably_ fine (because you can just load the reference files again, after fixing the compound, tissue, whatever), but for full-file data loaders (accucor/isocorr/mzXML), it is not clear to me that you would ever want some rows to commit and others to rollback [e.g. peakdata] .  Perhaps I am misunderstanding the issue?  Is there a defined issue, besides change description? [but proceed on, because I am on vacation]

**Comment by hepcat72** [comment]
And BTW, the django experts gave their stamp of approval to this plan WRT exception aggregation, the crux of which is an exception raise inside an atomic block that is caught outside (to trigger the rollback of the record load attempt that failed).  As long as that happens, they had no issue at all with continuing to attempt to load records (inside the outer atomic block that eventually rolls everything back - but that has nothing to do with their concern - just ours).

**Comment by lparsons** [comment]
@hepcat72 Is it feasible to get everything that has been reviewed merged, and then change these PRs to merge into `main`? It would make things easier for me to follow.

**Comment by hepcat72** [comment]
@lparsons - PR #887 (the one after this one) integrates the feature branch and main (well, main from 5 days ago - it doesn't include the merge from today, though that should contain no conflict).  Is it feasible to re-do that merge on the feature branch under this PR?  It of course could be done, but 887 involved a good bit of manual conflict resolution and I also had to write some new code to accomplish the full integration.  So perhaps, if you could describe the bits that are difficult to follow, I could assess the comparative difficulty?  It might be easier for me to resolve that confusion than redo 887...  Just a thought.  Let me know.

**Review by lparsons — APPROVED** [review]
OK, I sorted out the branch names now, so I think we're good here. Nice job buttoning up the atomic transaction rollback behavior.

**Pull request merged**
