### PR TITLE
Fixed migration conflict

### PR DESCRIPTION
**Pull request by hepcat72**
## Summary Change Description

I should probably change something about the merge process.  I keep running into this issue when both main and a branch pass, but when merged, encounter a migrations conflict.  Or maybe we can have a test that checks for migration files between the branch and main that start with the same number, but have different names...?

## Affected Issues/Pull Requests

- Resolves failed migration check test after a merge

## Review Notes

None

## Checklist

This pull request will be merged once the following requirements are met.  The
author and/or reviewers should uncheck any unmet requirements:

- Review requirements
  - Minimum approvals: 1 
  - No changes requested
  - All blocking issues resolved by reviewers
  - Specific reviewers: @__add_username_here__
    
  - Review period: 2 days 
- Associated issue/pull request requirements:
  
  - [x] All requirements in affected issues marked "resolved" are satisfied
  - [x] All required pull requests are merged *(or none)*
- Basic requirements
  
  - [x] [All linters pass](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#linting)
  - [x] [All tests pass](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#quality-control)
  - [x] All conflicts resolved
- Overhead requirements
  
  - [x] [New/changed method tests implemented/updated *(or no change)*](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#test-implementation)
  - [ ] [Updated *Unreleased* section of `changelog.md` *(or no change)*](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/changelog.md)
  - [x] [Migrations created & committed *(or no change)*](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#migration-process)

### CODE REVIEW

**Review by lparsons — COMMENTED** [review]
This PR seems to remove a migration, but I don't see a replacement. Is that correct?

**Comment by hepcat72** [comment]
> This PR seems to remove a migration, but I don't see a replacement. Is that correct?

It was a duplicate. The same migration existed under 2 different names in 2 branches before the merge. I think one started with 33 and the other with 34. I only deleted one of them.

**Comment by hepcat72** [comment]
> Strange that it ended up in two branches... good to go then.

Yeah. It could have been from the merge in of the parent branch. Then that parent had another PR merged in that created a conflict where 2 migrations with the same number had to be reordered. That's my best guess.

**Comment by hepcat72** [comment]
I'm trying to think of a test that can catch this potential migration conflict before merging. Can you reference the branch a branch will be merged into in a test? If we just have access to the migration file names of the branch merging in and the branch being merged, we can catch situations where 2 different migration files have the same number...

**Comment by lparsons** [comment]
I don't think it's too difficult an issue. It's fairly easy to catch and we should all take care when handling migrations. That said, merging main into a branch could be helpful, esp when three have been significant changes to main since the PR was branched.

**Comment by hepcat72** [comment]
It is a minor annoyance, for sure. I'm just surprised github doesn't have an automatic check for things like this.

**Pull request merged**
