### PR TITLE
Fixed an issue with DetailViews relating to MaintainedModel's threading.local data

### PR DESCRIPTION
**Pull request by hepcat72**
## Summary Change Description

Added a check and set of the class's attributes if not set.

## Affected Issues/Pull Requests

- Resolves an [issue](https://tracebase.slack.com/archives/C01LFSYQHN3/p1697049043747259) Lance encountered on main

## Review Notes

This might not be the best or only way to fix this issue.  According to [this stack post](https://stackoverflow.com/a/20643172/2057516), it suggests I might be setting the `threading.local` values in an unsupported way, but I'm pretty sure I'd looked it up.

This PR fixes this error when you try to look at any model's `DetailView`:
```
Traceback (most recent call last):
  File "/home/lparsons/mambaforge/envs/tracebase/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/lparsons/mambaforge/envs/tracebase/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/lparsons/mambaforge/envs/tracebase/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/lparsons/mambaforge/envs/tracebase/lib/python3.8/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/lparsons/mambaforge/envs/tracebase/lib/python3.8/site-packages/django/views/generic/detail.py", line 106, in get
    self.object = self.get_object()
  File "/home/lparsons/mambaforge/envs/tracebase/lib/python3.8/site-packages/django/views/generic/detail.py", line 52, in get_object
    obj = queryset.get()
  File "/home/lparsons/mambaforge/envs/tracebase/lib/python3.8/site-packages/django/db/models/query.py", line 431, in get
    num = len(clone)
  File "/home/lparsons/mambaforge/envs/tracebase/lib/python3.8/site-packages/django/db/models/query.py", line 262, in __len__
    self._fetch_all()
  File "/home/lparsons/mambaforge/envs/tracebase/lib/python3.8/site-packages/django/db/models/query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/lparsons/mambaforge/envs/tracebase/lib/python3.8/site-packages/django/db/models/query.py", line 69, in __iter__
    obj = model_cls.from_db(db, init_list, row[model_fields_start:model_fields_end])
  File "/home/lparsons/mambaforge/envs/tracebase/lib/python3.8/site-packages/django/db/models/base.py", line 515, in from_db
    new = cls(*values)
  File "/home/lparsons/Documents/projects/tracebase/DataRepo/models/maintained_model.py", line 650, in __init__
    self._maintained_model_setup(**kwargs)
  File "/home/lparsons/Documents/projects/tracebase/DataRepo/models/maintained_model.py", line 660, in _maintained_model_setup
    coordinator = self.get_coordinator()
  File "/home/lparsons/Documents/projects/tracebase/DataRepo/models/maintained_model.py", line 1119, in get_coordinator
    return cls._get_current_coordinator()
  File "/home/lparsons/Documents/projects/tracebase/DataRepo/models/maintained_model.py", line 1123, in _get_current_coordinator
    if len(cls.data.coordinator_stack) > 0:

Exception Type: AttributeError at /DataRepo/samples/1/
Exception Value: '_thread._local' object has no attribute 'coordinator_stack'
```

## Checklist

This pull request will be merged once the following requirements are met.  The
author and/or reviewers should uncheck any unmet requirements:

- Review requirements
  - Minimum approvals: 1 
  - No changes requested
  - All blocking issues resolved by reviewers
  - Specific reviewers: @__add_username_here__
    
  - Review period: 2 days 
- Associated issue/pull request requirements:
  
  - [x] All requirements in affected issues marked "resolved" are satisfied
  - [x] All required pull requests are merged *(or none)*
- Basic requirements
  
  - [x] [All linters pass](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#linting)
  - [x] [All tests pass](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#quality-control)
  - [x] All conflicts resolved
- Overhead requirements
  
  - [ ] [New/changed method tests implemented/updated *(or no change)*](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#test-implementation)
  - [ ] Added changes to *Unreleased* section of [`changelog.md`](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/changelog.md)
  - [x] [Migrations created & committed *(or no change)*](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#migration-process)

### CODE REVIEW

**Comment by hepcat72** [comment]
I have learned that the error had to do with the DetailView running in a different thread, where the initialization hadn't taken place. So for right now, the solution I implemented here should suffice, but I need to make sure that the thread instantiations happen in each new thread in an intentional way.

**Comment by hepcat72** [comment]
So, as a stop-gap, I think this PR is good.  It's only 3 lines of code.  I think that a good follow-up PR to this would be to remove direct access to the `threading.local` class attribute (`data`), e.g.: `MaintainedModel.data.coordinator_stack` and `MaintainedModel.data.default_coordinator`, from everywhere but 1 method, and in that method, address the thread initialization, if necessary.  Initialization only ever needs to happen once, the first time it's ever accessed.  After that, it's all managed automatically.

And there is already a method for coordinator default/stack initialization:
```
    @classmethod
    def _reset_coordinators(cls):
        cls.data.default_coordinator = MaintainedModelCoordinator()
        cls.data.coordinator_stack = []
```
but I currently only use it for tests.

**Review by lparsons — APPROVED** [review]
Thanks @hepcat72! I don't think I understand the details of the issue well enough to know if this is a "good" fix or not, but assuming it resolves the issue, I"ll approve so we can move forward with development.

**Comment by lparsons** [comment]
Thanks @hepcat72. I'm eager to get this fix in since it's holding up my progress at the moment. I can still work on things, but views are broken.

While I'm glad you are confident in the fix, I would caution you against believing there is nothing left to learn/understand. These low level changes to how the DB interface works are complex and we don't have a complete understanding how the Django ORM.

We should think about how urgent the full fix to this is. Josh is increasingly impatient about getting mzXML storage implement and having TraceBase in greater use. Each week that passes means more data is generated and not stored in TraceBase.

**Comment by hepcat72** [comment]
> Thanks @hepcat72. I'm eager to get this fix in since it's holding up my progress at the moment. I can still work on things, but views are broken.

Sorry. There's no holdup to merging this, which solves your problem.  I had suggested you merge this branch into your branch. I assumed you would do that.  But I'll merge this into main now.

> While I'm glad you are confident in the fix, I would caution you against believing there is nothing left to learn/understand. These low level changes to how the DB interface works are complex and we don't have a complete understanding how the Django ORM.

I don't know what has made you think I feel like there is nothing left to learn. That couldn't be further from the truth. I always feel like I can learn anything from anyone, which I often say in dancing, but that philosophy definitely applies here too, as in any topic. Part of the reason I'm excited to work on the better fix is the learning aspect.

> We should think about how urgent the full fix to this is. Josh is increasingly impatient about getting mzXML storage implement and having TraceBase in greater use. Each week that passes means more data is generated and not stored in TraceBase.

This fix solves the immediate problem and I am very confident that the full fix will only affect places where context managers are used for running loading code.

**Pull request merged**
