### PR TITLE
Submission validate page

### LINKED ISSUE #1123: Submission Validate page
### Inspiration

See #1034 and #1040

### Description

Modify the validate template to hide the peak annotations input

### Alternatives

None

### Dependencies

- Tracking Issue: #1120
- #1093

### Comment

None

-----

### Assumptions

1. List of assumptions that the code will not explicitly address/check
2. E.g. We will assume input is correct (explaining why there is no validation)

### Limitations

1. A list of things this work will specifically not do
2. E.g. This feature will only handle the most frequent use case X

### Affected Components

- change: File path or DB table ...
- add: Environment variable or server setting
- delete: External executable or cron job

### Requirements

- [ ] 1. List of numbered conditions to be met for the feature
- [ ] 2. E.g. Every column/row must display a value, i.e. cannot be empty
- [ ] 3. Numbers for reference & checkboxes for progress tracking

#### Interface Change description

None provided

#### Code Change Description

None provided

#### Tests

- [ ] 1. A description of at least one test for each requirement above.
- [ ] 2. E.g. Test for req 2 that there's an exception when display value is ''
- [ ] 3. Numbers for reference & checkboxes for progress tracking

### LINKED ISSUE #1125: Submission next-button hiding
### Inspiration

See #1034 and #1040

### Description

- Modify the submission start template to only show the "Next" button when results are presented
- Modify the submission validate template to show the "Next" button when results are presented (and present it as "Skip" when not displayed with results)

### Alternatives

None

### Dependencies

- Tracking Issue: #1120
- #1093

### Comment

None

-----

### Assumptions

1. List of assumptions that the code will not explicitly address/check
2. E.g. We will assume input is correct (explaining why there is no validation)

### Limitations

1. A list of things this work will specifically not do
2. E.g. This feature will only handle the most frequent use case X

### Affected Components

- change: File path or DB table ...
- add: Environment variable or server setting
- delete: External executable or cron job

### Requirements

- [ ] 1. List of numbered conditions to be met for the feature
- [ ] 2. E.g. Every column/row must display a value, i.e. cannot be empty
- [ ] 3. Numbers for reference & checkboxes for progress tracking

#### Interface Change description

None provided

#### Code Change Description

None provided

#### Tests

- [ ] 1. A description of at least one test for each requirement above.
- [ ] 2. E.g. Test for req 2 that there's an exception when display value is ''
- [ ] 3. Numbers for reference & checkboxes for progress tracking

### PR DESCRIPTION
**Pull request by hepcat72**
## Summary Change Description

Got the validate tab of the submission form working.

Details:

- Added a "mode" form field that can be either validate or autofill.  It is hidden and based on the active tab.
- Added conversion of the URL parameters to initial form mode field values.
- Edited the included css and javascript headers based on the active tab.
- Hid the peak annotations input.
- Eliminated the "expand" control for the status report.
- Fixed the "Next" button on the fill-in and validate tab pages.  (They were all going to "Fill In".)

subval

## Affected Issues/Pull Requests

- Resolves #1123
- Resolves #1125
- Merges into PR #1138
- Next PR: #1149

## Review Notes

See comments in-line.

## Checklist

This pull request will be merged once the following requirements are met.  The
author and/or reviewers should uncheck any unmet requirements:

- Review requirements
  - Minimum approvals: 1 
  - No changes requested
  - All blocking issues resolved by reviewers
  - Specific reviewers: @__add_username_here__
    
  - Review period: 2 days 
- Associated issue/pull request requirements:
  
  - [x] All requirements in affected issues marked "resolved" are satisfied
  - [x] All required pull requests are merged *(or none)*
- Basic requirements
  
  - [x] [All linters pass](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#linting)
  - [x] [All tests pass](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#quality-control)
  - [x] All conflicts resolved
- Overhead requirements
  
  - [x] [New/changed method tests implemented/updated *(or no change)*](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#test-implementation)
  - [ ] [Updated *Unreleased* section of `changelog.md` *(or no change)*](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/changelog.md)
  - [x] [Migrations created & committed *(or no change)*](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#migration-process)

### CODE REVIEW

**Review by lparsons — COMMENTED** [review]
The changes look good, though when I was testing, I ran into an exception. I uploaded an old study doc lying around, so no doubt it had some issues, however, throwing a ValueError in dev will mean a 500 error in production.

[study.xlsx](https://github.com/user-attachments/files/16619214/study.xlsx)

```
Environment:


Request Method: POST
Request URL: http://127.0.0.1:8000/DataRepo/submission

Django Version: 4.2.11
Python Version: 3.9.18
Installed Applications:
['DataRepo.apps.DatarepoConfig',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'DataRepo.tests.apps.test_apps.LoaderTestConfig',
 'django_extensions']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']



Traceback (most recent call last):
  File "/home/lparsons/miniforge3/envs/tracebase/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/lparsons/miniforge3/envs/tracebase/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/lparsons/miniforge3/envs/tracebase/lib/python3.9/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/lparsons/Documents/projects/tracebase/DataRepo/views/upload/submission.py", line 540, in dispatch
    return super(DataValidationView, self).dispatch(request, *args, **kwargs)
  File "/home/lparsons/miniforge3/envs/tracebase/lib/python3.9/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/lparsons/Documents/projects/tracebase/DataRepo/views/upload/submission.py", line 570, in post
    return self.form_valid(form)
  File "/home/lparsons/Documents/projects/tracebase/DataRepo/views/upload/submission.py", line 579, in form_valid
    study_data = self.get_download_data()
  File "/home/lparsons/Documents/projects/tracebase/DataRepo/views/upload/submission.py", line 642, in get_download_data
    xlsx_writer = self.create_study_file_writer(study_stream)
  File "/home/lparsons/Documents/projects/tracebase/DataRepo/views/upload/submission.py", line 2627, in create_study_file_writer
    raise ValueError(

Exception Type: ValueError at /DataRepo/submission
Exception Value: Cannot call create_study_file_writer when dfs_dict is not valid/created.
```

**Comment by hepcat72** [comment]
Ah, that makes sense.  This should be fixed in this PR, IMO.  Part of this PR was to determine running mode (autofill or validate) based on the page we're on.  When I implemented that logic, I skipped calling `determine_study_file_validation_readiness`, and inside there is where it checks if "dfs_dict is valid/created".  When it wasn't ready (i.e. when it was invalid), it automatically switch to autofill mode, which would fill in things like missing required columns and other sorts of things, which will not raise those exceptions.  I will need to:

- [ ] TODO: Check the doc readiness and call the repair methods when in validate mode, before validating.

**Comment by hepcat72** [comment]
Created #1173.  I know I wanted to make this update before merging, but I'm creating a number of issues RN from my meeting with Michael yesterday - and trying to merge a bunch of approved PRs.  This one will be top priority.  I added it to the submission flow phase 1 milestone.

**Comment by hepcat72** [comment]
Whoops. I see now the review was a comment. Well... shoot. I'll fix the one issue first thing.

**Pull request merged**
