### PR TITLE
Upgrade Django to 3.2.4, pin all requirements

### PR DESCRIPTION
**Pull request by lparsons**
## Summary Change Description

[Django 3.2.x is a Long Term Support (LTS) release](https://www.djangoproject.com/download/). The previous version, 3.1.8 had some security vulnerabilities that have been patched.

Pinning packages to specific versions makes it easier to create stable, repeatable environments. The [pip documentation has a good discussion on this](https://pip.pypa.io/en/latest/user_guide/#repeatability).

## Affected Issue Numbers

- [Dependabot alerts](https://github.com/Princeton-LSI-ResearchComputing/tracebase/security/dependabot)

## Code Review Notes

After updating, developers should update their virtual environments:

```bash
source .venv/bin/activate
pip install -r requirements/dev.txt
```

## Checklist

- [x] All issue requirements satisfied (or no linked issues)
- [x] [Linting passes](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#linting).
- [x] [Migrations created & committed *(or no model changes)*](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#migration-process)
- [x] [Tests implemented *(or no code changes)*](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#test-implementation)
- [x] [All tests pass](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#quality-control)

### CODE REVIEW

**Review by fkang-pu — APPROVED** [review]

**Comment by hepcat72** [comment]
Note, the [Dependabot alerts](https://github.com/Princeton-LSI-ResearchComputing/tracebase/security/dependabot) link in the issue description is broken.

**Review by hepcat72 — APPROVED** [review]

**Comment by lparsons** [comment]
Odd, the link for works for me:
image

**Comment by hepcat72** [comment]
> Odd, the link for works for me (see screenshot). Maybe it says something in the [Dependabot documentation](https://docs.github.com/en/code-security/supply-chain-security/managing-vulnerabilities-in-your-projects-dependencies/about-dependabot-security-updates). It's also listed under the "Security" tab at the top of the GitHub repo page.
> image

That is odd.  Perhaps it's a permissions issue:

dependabot-404

**Comment by lparsons** [comment]
> Yeah, I don't have the alerts tab on that Security page. I suspect you, as the repo admin, are the only one who can see it.

That may be so. Could you check now (refresh I guess)? I tried granting @hepcat72 and @jcmatese "Maintain" privileges.

**Comment by jcmatese** [comment]
> > Yeah, I don't have the alerts tab on that Security page. I suspect you, as the repo admin, are the only one who can see it.
> 
> That may be so. Could you check now (refresh I guess)? I tried granting @hepcat72 and @jcmatese "Maintain" privileges.

I get a 404 for the URL it resolves to https://github.com/Princeton-LSI-ResearchComputing/tracebase/security/dependabot

**Comment by lparsons** [comment]
> > Yeah, I don't have the alerts tab on that Security page. I suspect you, as the repo admin, are the only one who can see it.
> 
> That may be so. Could you check now (refresh I guess)? I tried granting @hepcat72 and @jcmatese "Maintain" privileges.

OK, I think I figured it out. There is a setting to allow certain people to see security vulnerabilities. @hepcat72 and @jcmatese are now on it, I'll try adding @fkang-pu as well.

**Review by jcmatese — APPROVED** [review]

**Comment by hepcat72** [comment]
> > > Yeah, I don't have the alerts tab on that Security page. I suspect you, as the repo admin, are the only one who can see it.
> > 
> > 
> > That may be so. Could you check now (refresh I guess)? I tried granting @hepcat72 and @jcmatese "Maintain" privileges.
> 
> OK, I think I figured it out. There is a setting to allow certain people to see security vulnerabilities. @hepcat72 and @jcmatese are now on it, I'll try adding @fkang-pu as well.

Now that I see the alerts, this is a great thing to have.  I was just looking at an abandonned branch and it alerted me to security vulnerabilities related to dependencies.

**Pull request merged**
