### PR TITLE
Load study multi

### LINKED ISSUE #478: Update `load_study` to work with isocorr files
### Inspiration

Studies that use isocorr data files cannot be properly loaded using the `load_study` command.

### Description

* Update the `loading.yaml` specification to include the flags/options needed to load isocorr data.
* Update the `load_study` command to parse the isocorr options.

### Comment

-----

### Assumptions

none

### Requirements

- [x] 1. The `python manage.py load_study` command on the command line should work for all accucor/isocorr files in the example_data directory

### Limitations

- This effort does not modify/update the studies' `loading.yaml` files in the data repo

### Affected Components

- `DataRepo/management/commands/load_study.py`
- `DataRepo/tests/test_models.py`

#### Interface Change description

none

#### Code Change Description

Should be straightforward.  Looks like already passes `isocorr_format`, but it was never tested. Probably only need to add to the yaml.

#### Tests

- [x] Make sure existing tests that call load_study work

### PR DESCRIPTION
**Pull request by hepcat72**
## Summary Change Description

Changes to get the ci test load of example data to work.

## Affected Issue Numbers

- Resolves #478

## Code Review Notes

This didn't actually require changes to load_study.pl.  All I had to do was update the data file it was running on in the tests.  I did not comprehensively update all the example data - only those that the tests run on (though neither did I check to see if the test cases encompass all the example data either).

I changed the header option in the yaml loading file for that data set.

The tests take so long, I am optimistically submitting before my second run using the working tag finishes.  It should succeed, theoretically.  If it doesn't, I'll go into draft after lunch.

Added tests to load the isocorr studies using load_study.

## Checklist

- [x] All issue requirements satisfied (or no linked issues)
- [x] [Linting passes](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#linting).
- [x] [Migrations created & committed *(or no model changes)*](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#migration-process)
- [x] [Tests implemented *(or no code changes)*](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#test-implementation)
- [x] [All tests pass](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#quality-control)
  - [x] Added tag `multi_working` to `StudyLoadingTests` and removed the broken tag

### CODE REVIEW

**Review by lparsons — APPROVED** [review]
Thanks to your prior self @hepcat72 for doing the work already! The changes here look good, but there is at least one test failure:
```
022-07-28T17:29:32.2708682Z ERROR: test_multi_label_isocorr_study (DataRepo.tests.test_models.StudyLoadingTests)
2022-07-28T17:29:32.2709302Z ----------------------------------------------------------------------
2022-07-28T17:29:32.2709662Z Traceback (most recent call last):
2022-07-28T17:29:32.2722350Z   File "/home/runner/work/tracebase/tracebase/DataRepo/tests/test_models.py", line 2221, in test_multi_label_isocorr_study
2022-07-28T17:29:32.2722825Z     call_command(
2022-07-28T17:29:32.2723595Z   File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/django/core/management/__init__.py", line 181, in call_command
2022-07-28T17:29:32.2724061Z     return command.execute(*args, **defaults)
2022-07-28T17:29:32.2724733Z   File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
2022-07-28T17:29:32.2725177Z     output = self.handle(*args, **options)
2022-07-28T17:29:32.2725628Z   File "/home/runner/work/tracebase/tracebase/DataRepo/management/commands/load_study.py", line 170, in handle
2022-07-28T17:29:32.2725998Z     call_command(
2022-07-28T17:29:32.2726622Z   File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/django/core/management/__init__.py", line 181, in call_command
2022-07-28T17:29:32.2727076Z     return command.execute(*args, **defaults)
2022-07-28T17:29:32.2727714Z   File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
2022-07-28T17:29:32.2728126Z     output = self.handle(*args, **options)
2022-07-28T17:29:32.2728590Z   File "/home/runner/work/tracebase/tracebase/DataRepo/management/commands/load_accucor_msruns.py", line 117, in handle
2022-07-28T17:29:32.2729007Z     loader = AccuCorDataLoader(
2022-07-28T17:29:32.2729454Z   File "/home/runner/work/tracebase/tracebase/DataRepo/utils/accucor_data_loader.py", line 145, in __init__
2022-07-28T17:29:32.2729854Z     self.sample_dict = self.get_db_samples()
2022-07-28T17:29:32.2730323Z   File "/home/runner/work/tracebase/tracebase/DataRepo/utils/accucor_data_loader.py", line 382, in get_db_samples
2022-07-28T17:29:32.2730695Z     raise (
2022-07-28T17:29:32.2731076Z DataRepo.utils.exceptions.MissingSamplesError: 1 samples are missing: bk
```

That doesn't seem to be a problem with any code but, perhaps just need to specify a sample to skip.

**Comment by hepcat72** [comment]
> Thanks to your prior self @hepcat72 for doing the work already! The changes here look good, but there is at least one test failure:
> 
> ```
> 022-07-28T17:29:32.2708682Z ERROR: test_multi_label_isocorr_study (DataRepo.tests.test_models.StudyLoadingTests)
> 2022-07-28T17:29:32.2709302Z ----------------------------------------------------------------------
> 2022-07-28T17:29:32.2709662Z Traceback (most recent call last):
> 2022-07-28T17:29:32.2722350Z   File "/home/runner/work/tracebase/tracebase/DataRepo/tests/test_models.py", line 2221, in test_multi_label_isocorr_study
> 2022-07-28T17:29:32.2722825Z     call_command(
> 2022-07-28T17:29:32.2723595Z   File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/django/core/management/__init__.py", line 181, in call_command
> 2022-07-28T17:29:32.2724061Z     return command.execute(*args, **defaults)
> 2022-07-28T17:29:32.2724733Z   File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
> 2022-07-28T17:29:32.2725177Z     output = self.handle(*args, **options)
> 2022-07-28T17:29:32.2725628Z   File "/home/runner/work/tracebase/tracebase/DataRepo/management/commands/load_study.py", line 170, in handle
> 2022-07-28T17:29:32.2725998Z     call_command(
> 2022-07-28T17:29:32.2726622Z   File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/django/core/management/__init__.py", line 181, in call_command
> 2022-07-28T17:29:32.2727076Z     return command.execute(*args, **defaults)
> 2022-07-28T17:29:32.2727714Z   File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
> 2022-07-28T17:29:32.2728126Z     output = self.handle(*args, **options)
> 2022-07-28T17:29:32.2728590Z   File "/home/runner/work/tracebase/tracebase/DataRepo/management/commands/load_accucor_msruns.py", line 117, in handle
> 2022-07-28T17:29:32.2729007Z     loader = AccuCorDataLoader(
> 2022-07-28T17:29:32.2729454Z   File "/home/runner/work/tracebase/tracebase/DataRepo/utils/accucor_data_loader.py", line 145, in __init__
> 2022-07-28T17:29:32.2729854Z     self.sample_dict = self.get_db_samples()
> 2022-07-28T17:29:32.2730323Z   File "/home/runner/work/tracebase/tracebase/DataRepo/utils/accucor_data_loader.py", line 382, in get_db_samples
> 2022-07-28T17:29:32.2730695Z     raise (
> 2022-07-28T17:29:32.2731076Z DataRepo.utils.exceptions.MissingSamplesError: 1 samples are missing: bk
> ```
> 
> That doesn't seem to be a problem with any code but, perhaps just need to specify a sample to skip.

Yep. I fixed it maybe an hour ago and was looking at the funconn issue while the tests reran locally when the fridge leak came to my attention.  Fix incoming.

**Comment by hepcat72** [comment]
Oh geez. What now? That one test passed locally. Going into draft again...

**Comment by hepcat72** [comment]
Well, I had to clear out my database to encounter that error (because of a `get_or_create`). Working on that now. Just out of curiosity, can we run the ci tests locally?

**Comment by lparsons** [comment]
> Well, I had to clear out my database to encounter that error (because of a `get_or_create`). Working on that now. Just out of curiosity, can we run the ci tests locally?

Sure, it's just a bunch of cli commands: https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/6bd06d83e3b3a1ad0f3de3d0cab845159272f70e/.github/workflows/tracebase-tests.yml#L79-L122

**Comment by hepcat72** [comment]
> > Well, I had to clear out my database to encounter that error (because of a `get_or_create`). Working on that now. Just out of curiosity, can we run the ci tests locally?
> 
> Sure, it's just a bunch of cli commands:
> 
> https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/6bd06d83e3b3a1ad0f3de3d0cab845159272f70e/.github/workflows/tracebase-tests.yml#L79-L122

No, I mean, in a test environment, so I don't have to modify my development database for my sandbox...

**Comment by hepcat72** [comment]
I.e. Running those commands doesn't reproduce the error because of the contents of my DB. Once I blew away my DB, now I see the error.

**Comment by hepcat72** [comment]
The push should (again) theoretically pass.  The error I fixed was novel - an edge case we hadn't encountered before, and was due to a non-default collection time header causing an error that we couldn't see due to an undefined variable it causes in a second nested except block. 🙄

**Comment by hepcat72** [comment]
OK. Finally.

**Comment by hepcat72** [comment]
Nice to see that green checkmark again!

**Comment by hepcat72** [comment]
Merged and pushed locally. (Too bad the PR doesn't reflect that - because it's to a different branch.  Oh well.)

**Comment by lparsons** [comment]
> No, I mean, in a test environment, so I don't have to modify my development database for my sandbox...

Create a separate db and separate config to point there?

**Comment by hepcat72** [comment]
Yeah, I guess. I suppose I'm wondering if there's a docker container for the tests, like there is for the linting... Doesn't matter. Just curious.

**Pull request closed without merging**
