### PR TITLE
Investigate call_command in test harness

### LINKED ISSUE #71: Command Tests investigation
### Feature Inspiration

It would be nice to test the end result product of loader commands , that did not involve replicating data of the file or the logic of the command or loader class in the test itself.  Sometimes, you need to test the final results/data and not individual methods, especially if the method/logic may not have been coded (#70 ).

### Feature Description

Investigate [django.core.management.call_command](https://docs.djangoproject.com/en/3.2/ref/django-admin/#running-management-commands-from-your-code)  within the test harness

### Alternatives Considered

A brief description of any alternative features that may accomplish the same
ultimate goal.

### Comment

-----

### Assumptions

- List of assumptions made WRT the code
- E.g. We will assume input is correct (explaining why there is no validation)

### Requirements

- List of conditions to be met for the feature
- E.g. Every column/row must display a value, i.e. cannot be empty

### Limitations

- A list of things this work will specifically not do
- E.g. This feature will only handle the most frequent use case X

### Affected/Changed Components

- Files
- Environment variables
- External executables
- Database tables
- Cron job settings
- Etc.

#### GUI Change description

Describe changes the user will see.

#### Code Change Description *(Pseudocode optional)*

Describe code changes planned for the feature.

#### Tests

A test should be planned for each requirement (above), where possible.

### PR DESCRIPTION
**Pull request by jcmatese**
## Summary Change Description

This is an investigation into the possibility of validation of the predicted/expected results of a command script.

## Affected Issue Numbers

- Resolves #71

## Code Review Notes

setUp and test organization is still not fully understood (by me).  When I employed call_command in the setUp, they appeared to be  employed for every individual test (so full file loads of both compound and samples for every single test, which seems inefficient).  So perhaps a different strategy or organization could be tried? **NOTE**: now employing  [`setUpTestData`](https://docs.djangoproject.com/en/3.2/topics/testing/tools/#django.test.TestCase.setUpTestData)

## Checklist

- [x] All issue requirements satisfied (or no linked issues)
- [x] [Linting passes](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#linting).
- [x] [Migrations created & committed *(or no model changes)*](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#migration-process)
- [x] [Tests implemented *(or no code changes)*](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#test-implementation)
- [x] [All tests pass](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#quality-control)

### CODE REVIEW

**Comment by jcmatese** [comment]
I think I need to investigate [setUpClass](https://docs.python.org/3/library/unittest.html#unittest.TestCase.setUpClass)

**Comment by jcmatese** [comment]
> I think I need to investigate [setUpClass](https://docs.python.org/3/library/unittest.html#unittest.TestCase.setUpClass)

Did not work for me at first attempt .  Threw
```
django.db.utils.IntegrityError: duplicate key value violates unique constraint "DataRepo_compound_name_key"
DETAIL:  Key (name)=(C16:0) already exists.
```
Suggesting that it was executing the command multiple times, I suppose.

**Comment by lparsons** [comment]
Another option would be [`setUpTestData'](https://docs.djangoproject.com/en/3.2/topics/testing/tools/#django.test.TestCase.setUpTestData), but I haven't looked into either too carefully.

**Comment by jcmatese** [comment]
> Another option would be [`setUpTestData`](https://docs.djangoproject.com/en/3.2/topics/testing/tools/#django.test.TestCase.setUpTestData), but I haven't looked into either too carefully.

Independently found and tested that and seems like it works; pushing that instead

**Review by fkang-pu — APPROVED** [review]

**Review by lparsons — APPROVED** [review]
LGTM - might be nice to merge #78 and the uncomment that test.

**Pull request merged**
