### PR TITLE
Lazy-update functionality for maintained field values

### LINKED ISSUE #553: Create getters that lazy-populate maintained fields (like the cached_function decorators do)
### Inspiration

While implementing part of issue 460, it occurred to me that the calculation of the maintained field did not have to be restricted to running `rebuild_maintained_fields` and calling `perform_buffered_updates` at the end of a load script.  Both of those actions can be time-consuming.  The rebuild (while it can be directed to operate on maintained fields with a specific label) operates on fields that are already calculated (which is a waste of resources), and the buffered updates operate on fields that is not immediately necessary.  And I realized that the calculations could really be done piecemeal anytime, and it made me think of how the cached_function decorators work.  That served to inspire this issue...

### Description

Add automatically create getter methods to MaintainedModel for each maintained field to lazy-create the values on-demand if the field is `None`.

### Alternatives

The alternatives are, as mentioned in the `Inspiration` section:

- Manually run `rebuild_maintained_fields` whenever missing values are noticed
- Continue to run `perform_buffered_updates` at the end of load scripts
- Go into the console and call `record.save()` to surgically auto-update maintained fields in specific records
- Create one-off getter functions for every maintained field in its model class (which has already been done in 2 cases)

### Dependencies

none

### Comment

A good bit of discussion related to this feature was had regarding the infusate and tracer name fields, but that discussion was also related to a separate issue: unrelated code depended on a maintained field to have a non-null value and raised a 500 error when it was not populated (which had been due to a separate loading bug that was fixed, but regardless, prompted the discussion surrounding this feature, which in that context, this feature additionally served to mitigate erroneous none-values in the future)...

See discussion in PR #533

While discussing strategies for dealing with unpopulated `Infusate.name` fields, a few things were noted:

- Infusate.name has `null=True` in the model
  - This is required in order to be a maintained field because the name is composed in an autoupdate method
  - Other dataframes code assumes it's never null, which was causing 500 errors and prompted the null tolerance tests to be added
- The options for resolving that issue were:
  - Enforce `Infusate.name` values at the end of the load script
  - Make Infusate.name to be `null=False` (and require the name to be constructed in the loading code)
  - Write the code to allow/account-for the possibility that the name could be null
  - I suggested that the dataframes code use either `Infusate.get_name()` or `Infusate.pretty_name()` to retrieve the name, thereby making the view *always* have a value.

That specific issue is not specifically the reason behind the creation of this issue, but it did serve as an impetus behind a design that would facilitate the resolution of issue #460.

-----

### Assumptions

- List of assumptions that the code will not explicitly address/check
- E.g. We will assume input is correct (explaining why there is no validation)

### Requirements

- [ ] 1. List of numbered conditions to be met for the feature
- [ ] 2. E.g. Every column/row must display a value, i.e. cannot be empty
- [ ] 3. Numbers for reference & checkboxes for progress tracking

### Limitations

- A list of things this work will specifically not do
- E.g. This feature will only handle the most frequent use case X

### Affected Components

A tentative list of anticipated repository items that will be changed, labeled
with "add", "delete", or "change".  One item per line.  (Mostly, this will be a
list of files.)

- change: File path or DB table ...
- add: Environment variable or server setting
- delete: External executable or cron job

#### Interface Change description

Describe changes to usage. *E.g. GUI/command-line changes*

#### Code Change Description

Describe code changes planned for the feature. *(Pseudocode encouraged)*

#### Tests

- [ ] 1. A description of at least one test for each requirement above.
- [ ] 2. E.g. Test for req 2 that there's an exception when display value is ''
- [ ] 3. Numbers for reference & checkboxes for progress tracking

### PR DESCRIPTION
**Pull request by hepcat72**
## Summary Change Description

This PR adds the ability to correct missing maintained field values as they are encountered/requested by implementing a property for each maintained field to retrieve its value.  Using that property instead of the field directly allows the fields self-correct their values if they are ever found to be missing values.

## Affected Issue Numbers

- Established the foundation for issue #460 (making the remainder very straightforward to resolve) This is the primary intent of this PR
- Resolves #553
- Implements temporary fix for #513

## Code Review Notes

Put simply, here's what these code changes do:

1. For every Model's function that has the `@maintained_field_function` decorator, a property is created named `get_{field name}`, and that function behaves like the `@cached_function` does: if the DB field that's maintained is `None`, it uses the decorated function to initialize its value.  Otherwise, it just returns the value in the database field
2. In the sample table loader code, the infusate, tracer, and tracerlabel name fields are checked, and if they don't have a value, a warning is issued with a suggested fix

Note that I decided on a warning in item 2 because:
1. the resolution should be easy,
2. It's a temporary fix that currently should never be needed for a [bug that needs to be fixed elsewhere](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/e1bf2644e3e9b77bf40a7af8590495cf97daff2a/DataRepo/tests/test_queryset_to_dataframes.py#L273-L287).

I actually create 2 properties for each maintained database field.  For example, for the Infusate.name DB field:

- `Infusate.get_name` - To get the name and update it if it's none in the DB
- `Infusate.refresh_name` - To force an update even if it has a value

In both cases, it's a full-on autoupdate and will propagate the change to affected model fields (using unchanged existing code simply by calling `.save()`).

I changed affected places where fields (or their update functions) were accessed to take advantage of this new maintenance feature.

There is one thing to note however: if a field value *should* be None, and that is the output of the updater function, this will always recalculate the value for the field when the getter property is called.  While this should not happen in existing cases, I *could* implement a way to either keep a value for a period of time (similar to caching) or figure out a way to know when it *should* be `None`.

This code was written to be safe: it will not create the property if either the derived or super class has a property or attribute by that name.

Also note, I had written a concrete version of this code in `DataRepo.models.infusate.py` called `get_name`, which I removed, and I am relying on the tests I wrote for that to test this new code, which is why I am checking the "tests written" box below.

## Checklist

- [x] All issue requirements satisfied (or no linked issues)
- [x] [Linting passes](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#linting).
- [x] [Migrations created & committed *(or no model changes)*](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#migration-process)
- Tests
  - [x] [Tests implemented *(or no code changes)*](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#test-implementation)
  - [x] [All *multi_working* tag tests pass locally](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#quality-control)
  - [x] All example load tests pass (remotely) *(or their failures predated and are unrelated to this branch)*
  - [x] `@tag("multi_working")` added to newly passing test functions/classes *(or no newly passing tests)*
  - [x] `@tag("multi_broken")`, `@tag("multi_unknown")`, or `@tag("multi_mixed")` removed from newly passing test functions/classes *(or no newly passing tests)*

### CODE REVIEW

**Comment by hepcat72** [comment]
- [ ] Rebase off the soon-to-be-merged #570 and then in this branch, delete `Tracer.get_name`

**Comment by hepcat72** [comment]
Rebased off main, which changed the git log. A lot of the commits can be ignored.  The diff won't show them.

**Comment by hepcat72** [comment]
So I did this rebase before I knew there was an erroneous push to main, thus the errors it introduced in main are now also here...  I'll get it all sorted out...

**Comment by hepcat72** [comment]
Man, fixing the conflicts was not straightforward at all.  The auto-merge's rendering of the conflicts was way off.  I hope we don't let this PR sit much longer.  The further away this gets, the more difficult the resolution of conflicts.

**Comment by hepcat72** [comment]
This PR is getting increasingly difficult to keep up to date. I still want to merge it. Can we review this now that I gave the MaintainedModel usage presentation, or do we want to also have the [Understanding Maintained Model presentation](https://docs.google.com/presentation/d/1Asn7zhByF5Le2Y44c0pj9JuMLgfr3ovMXvTIuxzxIfY/edit?usp=share_link)?

**Comment by lparsons** [comment]
I'll add this as a point of discussion for our next meeting. It would be nice to have a summary of the reasoning behind the change and the implementation strategy.

**Pull request closed without merging**
