### PR TITLE
Added the ability to disable the upload page (for the public instance)

### LINKED ISSUE #1334: Create environment variable for enabling the upload interface
### Inspiration

The public instance of tracebase should not accept data submissions.

### Description

Add an environment variable to be able to enable/disable the upload interface.  When disabled, simply don't show the upload option in the nav bar at the top.

### Alternatives

For transparency, perhaps instead, the upload in the nav bar should be grayed out with a tooltip upon hover?  This is probably not the way to go, since the public is never intended to even think about upload... then again, it could be an opportunity to link them to the repo and encourage people to run their own instance...

### Dependencies

None

### Comment

None

-----

### Assumptions

1. List of assumptions that the code will not explicitly address/check
2. E.g. We will assume input is correct (explaining why there is no validation)

### Limitations

1. A list of things this work will specifically not do
2. E.g. This feature will only handle the most frequent use case X

### Affected Components

- change: File path or DB table ...
- add: Environment variable or server setting
- delete: External executable or cron job

### Requirements

- [ ] 1. List of numbered conditions to be met for the feature
- [ ] 2. E.g. Every column/row must display a value, i.e. cannot be empty
- [ ] 3. Numbers for reference & checkboxes for progress tracking

#### Interface Change description

None provided

#### Code Change Description

None provided

#### Tests

- [ ] 1. A description of at least one test for each requirement above.
- [ ] 2. E.g. Test for req 2 that there's an exception when display value is ''
- [ ] 3. Numbers for reference & checkboxes for progress tracking

### PR DESCRIPTION
**Pull request by hepcat72**
## Summary Change Description

Added an environment variable (READONLY) that controls whether the site is public or not (i.e. whether it accepts uploads and has the ability to edit data).

Details:

- Renamed the context processor method from debug to "globals" and made it return the value of the READONLY global variable from the settings.
- Added a READONLY global variable that defaults to False.
- Updated the `.env.example` file to include the READONLY variable.
- Updated the navbar template to not render the Upload and Admon links/buttons.

Before:

uploadbefore

After:

uploadafter

## Affected Issues/Pull Requests

- Resolves #1334
- Merges into main

## Review Notes

See comments in-line.

## Checklist

This pull request will be merged once the following requirements are met.  The
author and/or reviewers should uncheck any unmet requirements:

- Review requirements
  - Minimum approvals: 1 
  - No changes requested
  - All blocking issues resolved by reviewers
  - Specific reviewers: @__add_username_here__
    
  - Review period: 2 days 
- Associated issue/pull request requirements:
  
  - [x] All requirements in affected issues marked "resolved" are satisfied
  - [x] All required pull requests are merged *(or none)*
- Basic requirements
  
  - [x] [All linters pass](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#linting)
  - [x] [All tests pass](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#quality-control)
  - [x] All conflicts resolved
- Overhead requirements
  
  - [x] [New/changed method tests implemented/updated *(or no change)*](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#test-implementation)
  - [ ] [Updated *Unreleased* section of `changelog.md` *(or no change)*](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/changelog.md)
  - [x] [Migrations created & committed *(or no change)*](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#migration-process)

### CODE REVIEW

**Comment by hepcat72** [comment]
@fkang-pu - would you mind a quick review for this one?

**Review by fkang-pu — APPROVED** [review]
The changes look good to me, though I didn't test this PR.

**Comment by fkang-pu** [comment]
@hepcat72 John and I just discussed how to disable submission webpage in case somebody copied/pasted submission url to the website for public instance for tracebase. We discussed 2 options: 1. remove submission path from `urls.py` file;  2. add a block of code to `submission.html` to check `READONLY` value first, and raise an error and exit if READONLY is True.  The option 2 seems better. Just share what we discussed as they are related to this PR.

**Comment by hepcat72** [comment]
> @hepcat72 John and I just discussed how to disable submission webpage in case somebody copied/pasted submission url to the website for public instance for tracebase. We discussed 2 options: 1. remove submission path from `urls.py` file; 2. add a block of code to `submission.html` to check `READONLY` value first, and raise an error and exit if READONLY is True. The option 2 seems better. Just share what we discussed as they are related to this PR.

Thanks.  I had similar thoughts this morning before I read your reply.  I like the second suggestion.  I may create a separate issue for that, instead of edit this PR.

**Pull request merged**
