### PR TITLE
Added caret to rows-per-page button

### LINKED ISSUE #369: Fix rows per page button appearance
The select list caret for the rows per page drop-down (as it appeared in the client-side BST pagination) is missing.  I can probably get it back by creating a custom widget, as described here:

https://stackoverflow.com/questions/45424162/listing-a-choicefield-in-django-as-button

...in forms.AdvSearchPageForm.

I should probably supply the BST caret icon inside the `new` method.

_Originally posted by @hepcat72 in https://github.com/Princeton-LSI-ResearchComputing/tracebase/pull/368#r806064773_

### PR DESCRIPTION
**Pull request by hepcat72**
## Summary Change Description

I overloaded the Django select widget in order to make the rows per page select list button look like all the other BST CSS stylized controls.

## Affected Issue Numbers

- Resolves #369

## Code Review Notes

I had to keep the input element in order to be able to always send it in the page form because Django doesn't automatically include values from buttons unless they're clicked.  This meant I needed some javascript to cause the button-click to update the input tag.

The code should be very easy to revert.  Just swap the default widget back in and optionally delete the widget templates and the added widget class from forms.py.

Here's what it looked like before the fix:

ssbeforerppfix

Here's Bootstrap-table's appearance:

bstrppsl

And here is our server-side pagination with the overloaded widget:

ssrppsl2

## Checklist

- [x] All issue requirements satisfied (or no linked issues)
- [x] [Linting passes](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#linting).
- [x] [Migrations created & committed *(or no model changes)*](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#migration-process)
- [ ] [Tests implemented *(or no code changes)*](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#test-implementation)
- [x] [All tests pass](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#quality-control)

### CODE REVIEW

**Review by lparsons — APPROVED** [review]
Nice visual cleanup.

**Review by fkang-pu — APPROVED** [review]
Nice work!

**Comment by hepcat72** [comment]
I know John's busy with HTSEQ.  OK if I merge this?

**Comment by jcmatese** [comment]
> I know John's busy with HTSEQ. OK if I merge this?

Sorry, yes please proceed without me

**Comment by lparsons** [comment]
> I know John's busy with HTSEQ. OK if I merge this?

Maybe a quick ping of @jcmatese?

**Pull request merged**
