### PR TITLE
Fixed all of the column overrun issues in the templates

### LINKED ISSUE #984: Column Overruns on various pages
### Problem

The column width is too narrow for the longest words in the treatments (protocols): `carboxymethylcellulose` (randomly encountered - so perhaps there's a longer word?).  The infusates column has the same issue, so probably all columns could potentially have this issue.

There are actually multiple pages that have these overruns...

### Steps to reproduce

1. tracebase-dev.princeton.edu
2. Click the Studies page (currently, the default order shows the problem on the first page of studies)

### Current behavior

treatments:
column_overrun

infusates:
overrun_infusates

Animals:
Animals

Studies:
study_summary

### Expected behavior

The column width should dynamically accommodate the longest word.

### Suggested Change

None provided

### Comment

None

-----

### Assumptions

1. List of assumptions made WRT the code
3. E.g. We will assume input is correct (explaining why there is no validation)

### Limitations

1. A list of things this work will specifically not do
2. E.g. This feature will only handle the most frequent use case X

### Affected Components

- change: File path or DB table ...
- add: Environment variable or server setting
- delete: External executable or cron job

### Requirements

- [ ] 1. List of numbered conditions to be met for the feature
- [ ] 2. E.g. Every column/row must display a value, i.e. cannot be empty
- [ ] 3. Numbers for reference & checkboxes for progress tracking

#### GUI Change description

None provided

#### Code Change Description

None provided

#### Tests

- [ ] 1. A description of at least one test for each requirement above.
- [ ] 2. E.g. Test for req 2 that there's an exception when display value is ''
- [ ] 3. Numbers for reference & checkboxes for progress tracking

### PR DESCRIPTION
**Pull request by hepcat72**
## Summary Change Description

Basically, I just removed the classes defining a minimum and maxomum percentage width, e.g.: '<th class="min-vw-3 max-vw-10" ...'.

## Affected Issues/Pull Requests

- Resolves #984
- Merges into main

## Review Notes

See comments in-line.

## Checklist

This pull request will be merged once the following requirements are met.  The
author and/or reviewers should uncheck any unmet requirements:

- Review requirements
  - Minimum approvals: 1 
  - No changes requested
  - All blocking issues resolved by reviewers
  - Specific reviewers: @__add_username_here__
    
  - Review period: 2 days 
- Associated issue/pull request requirements:
  
  - [x] All requirements in affected issues marked "resolved" are satisfied
  - [x] All required pull requests are merged *(or none)*
- Basic requirements
  
  - [x] [All linters pass](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#linting)
  - [x] [All tests pass](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#quality-control)
  - [x] All conflicts resolved
- Overhead requirements
  
  - [x] [New/changed method tests implemented/updated *(or no change)*](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#test-implementation)
  - [ ] [Updated *Unreleased* section of `changelog.md` *(or no change)*](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/changelog.md)
  - [x] [Migrations created & committed *(or no change)*](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#migration-process)

### CODE REVIEW

**Review by lparsons — APPROVED** [review]
Seems like a reasonable fix to me.

**Comment by hepcat72** [comment]
> Seems like a reasonable fix to me.

In the meeting last week, Fan mentioned that she had added the limits to try and get every column to display without horizontal scrolling. She seemed to indicate that she might like to implement an alternate fix, though she admitted she had other things to work on. I can't recall if she was ok with merging this in the interim.

**Comment by fkang-pu** [comment]
> > Seems like a reasonable fix to me.
> 
> In the meeting last week, Fan mentioned that she had added the limits to try and get every column to display without horizontal scrolling. She seemed to indicate that she might like to implement an alternate fix, though she admitted she had other things to work on. I can't recall if she was ok with merging this in the interim.

I didn't test this PR directly, but have a local branch to test latest version of Bootstrap-table (23.2.). I just tested study and animal pages with/without column width control. Removing column width control (implemented in this PR) is a better solution. The column width control I added more than 1 year ago seemed to have pros for displaying study/animal tables at that time, but failed to see the cons (e.g. column value overrun) when more data were loaded. 

I agree we should merge this PR.

The main issue I encountered with displaying a wide table is that Bootstrap's word-break/word-wrap doesn't work with underscore (but working with space or hyphen). The long names contains underscore (e.g. some names for study, animal, tissue) just push the column wider. I still don't have a solution for it.

**Comment by hepcat72** [comment]
> > > Seems like a reasonable fix to me.
> > 
> > 
> > In the meeting last week, Fan mentioned that she had added the limits to try and get every column to display without horizontal scrolling. She seemed to indicate that she might like to implement an alternate fix, though she admitted she had other things to work on. I can't recall if she was ok with merging this in the interim.
> 
> I didn't test this PR directly, but have a local branch to test latest version of Bootstrap-table (23.2.).

Oh yeah, that's right. I forgot Fan suggested we update to the latest bootstrap table. I don't think I created an issue for that yet.

**Pull request merged**
