### PR TITLE
PeakGroup Advanced Search Results column changes

### LINKED ISSUE #314: Reorganize PeakData advanced search result columns
### Feature Inspiration

The result tables should help the researcher focus on the most important and relevant details for the specific data they are viewing. Reducing the default columns displayed and grouping the columns will help to make the organization of the table more intuitive.

### Feature Description

By default, show the following columns, with darker lines separating the groups. The group names are for clarification in this issue, but don't need to be displayed on the actual page.

Row Identification - Details that identify what this row of data describes
* Sample
* Tissue
* Compound Name (not pg name)
* Labeled Element Count

Data - The data collected/calculated for this row
* Corrected Abundance
* Fraction

Metadata - most commonly used metadata for grouping, etc.
* Genotype
* Feeding Status
* Treatment
* Tracer
* Study

Additional columns should be included in the appropriate group, but not displayed by default.

### Alternatives Considered

None

### Comment

image

-----

### Assumptions

none

### Requirements

```
Legend:

* Initially hidden
^ Add
- Bold border

Order:

*Animal
Sample
Tissue
*Peak Group
^Compound Name
*Measured Compound(s)
Labeled Element:Count
*Peak Group Set Filename
-
*Raw Abundance
Corrected Abundance
Fraction
*Median M/Z
*Median RT
-
*Formula
Genotype
*Sex
*Age (weeks)
Feeding Status
Treatment
*Diet
*Body Weight (g)
Tracer Compound
*Tracer Infusion Rate (ul/min/g)
*Tracer Infusion Concentration (mM)
Study
```

### Limitations

none

### Affected/Changed Components

- peakdata.html
- peakdata.tsv

#### GUI Change description

Reordered columns, column group outlines, a new column, and initially hidden columns.

#### Code Change Description *(Pseudocode optional)*

Same as the recent peakgroup format changes.

#### Tests

none

### LINKED ISSUE #315: Reorganize PeakGroup advanced search result columns
### Feature Inspiration

The result tables should help the researcher focus on the most important and relevant details for the specific data they are viewing. Reducing the default columns displayed and grouping the columns will help to make the organization of the table more intuitive.

### Feature Description

By default, show the following columns, with darker lines separating the groups. The group names are for clarification in this issue, but don't need to be displayed on the actual page.

Row Identification - Details that identify what this row of data describes
* Sample
* Tissue
* Compound Name (not pg name)
* Labeled Element

Data - The data collected/calculated for this row
* Total Abundance
* Enrichment Fraction
* Enrichment Abundance
* Normalized Labeling

Metadata - most commonly used metadata for grouping, etc.
* Genotype
* Feeding Status
* Treatment
* Tracer
* Study

Additional columns should be included in the appropriate group, but not displayed by default.

### Alternatives Considered

None

### Comment

image

-----

### Assumptions

none

### Requirements

Column details

```
Legend:

^ added column
* hidden column
- darker border

Column order:

*Animal
Sample
Tissue
*Peak Group
^Compound Name
*Measured Compound(s)
Labeled Element
*Peak Group Set Filename
-
Total Abundance
Enrichment Fraction
Enrichment Abundance
Normalized Labeling
-
*Formula
Genotype
*Sex
Feeding Status
*Diet
Treatment
*Body Weight (g)
*Age (weeks)
Tracer Compound
*Tracer Infusion Rate (ul/min/g)
*Tracer Infusion Concentration (mM)
Study
```

Add the added column to the download

### Limitations

none

### Affected/Changed Components

- `peakgroups.html`
- `peakgroups.tsv`

#### GUI Change description

Peak group column order, default hidden columns, and added compound name column.

#### Code Change Description *(Pseudocode optional)*

Simple template changes.  I will explore "border-collapse" for the dark border.

#### Tests

none - template code.

### PR DESCRIPTION
**Pull request by hepcat72**
## Summary Change Description

Rearranged results columns, set some columns to initially be hidden, and created column groups with a bold border.  Also added a Compound.name column for both the html and tsv templates.

Here's an example of what you should see (after the page finishes fully loading):

pgreorg

## Affected Issue Numbers

- Resolves #314
- Resolves #315

## Code Review Notes

I have not tested what happens when an entire column group is completely hidden.  Probably should do that.

Personally, I think the distinction between "identifying data" and "metadata" is debatable.  I would have put "Study" in the identifying data, had it not been explicitly categorized in the issue as metadata.

Any column ordering/grouping is open for debate.

## Checklist

- [x] All issue requirements satisfied (or no linked issues)
- [x] [Linting passes](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#linting).
- [x] [Migrations created & committed *(or no model changes)*](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#migration-process)
- [x] [Tests implemented *(or no code changes)*](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#test-implementation)
- [x] [All tests pass](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#quality-control)

### CODE REVIEW

**Comment by hepcat72** [comment]
Well... first issue... If you completely hide an entire column group (set span to 0), it apparently has a mnimum of 1, so there's an extra 1-col group that is squeezed in.

Also, I neglected to remove a console debug statement.

- [ ] Address 0-span edge case
- [ ] Remove debug console print

**Comment by lparsons** [comment]
> Personally, I think the distinction between "identifying data" and "metadata" is debatable. I would have put "Study" in the identifying data, had it not been explicitly categorized in the issue as metadata.

Just for some clarification on this:
* The row of data (measured and calculated values) is "identified" by the sample being tested (column in AccuCor) and the compound being measured (row in AccuCor)
* The addition of "Tissue" is there to assist with identifying the sample (but is certainly metadata). Moving study there may make sense too, but for now it was decided that would be more distracting than helpful.
* "Labeled Element" is also there to help identify the relevant labeling of the measured compound (and is also certainly metadata).

**Comment by lparsons** [comment]
@hepcat72 I'm going to hold off reviewing until you have completed your testing, let us know when it's ready for review.

**Comment by hepcat72** [comment]
> @hepcat72 I'm going to hold off reviewing until you have completed your testing, let us know when it's ready for review.

Oh, sorry. I finished with commit 731e4ec above your last comment.

**Comment by hepcat72** [comment]
I could have tried to delete the `colgroup` element or implemented a dynamic requirement, but I didn't think it was worth the effort. The only thing I'm not terribly satisfied with was the selection of `Total Abundance` as the column that could not be hidden in the middle group...

**Review by lparsons — APPROVED** [review]
Wow, looks great!

**Comment by hepcat72** [comment]
Geez. I think I rebased in the wrong direction... ugh oh well... can fix it later if anyone finds anything I guess. NBD

**Comment by hepcat72** [comment]
I also somehow accidentally merged in the changes from the branch for #314.  I felt like I was "done" over an hour ago.  I think I am just tired.

**Comment by hepcat72** [comment]
Ugh, what a mess.  I can't even figure out how to view the changes...

**Comment by lparsons** [comment]
@hepcat72 Looks like there was a `--force push` to `main`. I'd like to revert that. The last "good" revision of `main` I have is:
```
b7a059a - (HEAD -> main) Merge pull request #324 from Princeton-LSI-ResearchComputing/superlinter_slim (2 hours ago) <Robert Leach>
```
I'm happy to force push that to reset things and then we can clean up these pull requests. However, I want to make sure that won't cause you any extra headache.

**Comment by hepcat72** [comment]
I know I did a force push. That's necessary in the usual case after a "normal" rebase. I'll have to do something similar (if I can) to my 2 branches `pg_col_changes` and/or `pd_col_changes` because not only did I rebase in the wrong direction, I forgot I'd branched `pd_col_changes` off `pg_col_changes`.  I think I rebased main off of `pd_col_changes`. And I think I may have (though I'm not sure) done the opposite rebase WRT those other 2 branches. I think I should have stopped working at 6pm last night when I was tired instead of try and get`pd_col_changes` to a stopping point. I was too exhausted.

Anyway, yeah, fix main and I'll figure out how to fix my branches...

**Pull request merged**
