### PR TITLE
FCirc Multi 3 - Validation Database Changes

### LINKED ISSUE #395: Update FCirc output format to accommodate data with multiple labels per tracer
### Feature Inspiration

Experiments that use tracers with multiple labels will have multiple Ra/Rd values per Animal, one for each labeled element. This requires an update to the output table, which right now only displays one set of values per serum sample.

### Feature Description

- Fcirc will need to incorporate labeled element into calculations, and display data from a single sample in a different row for each labeled element.
- Fcirc(intact) is split by element
- Fcirc(average) is split by element

Examples
* [google slides describing expected outputs](https://docs.google.com/presentation/d/1LjFfvoWVjKwN434eZFGzi2vHFO1P2VitOE8xNc92Cz4/edit?usp=sharing)
* [google sheet of example calculations](https://docs.google.com/spreadsheets/d/1OfwWCgYlLi3XH9QS62ekn-dlEyldwj7fV260Gp2yFjY/edit?usp=sharing)

### Comment

NOTE: This may be broken into multiple issues to track the changes required to the functions computing the values separately from the changes to the views.

-----

### Assumptions

- List of assumptions made WRT the code
- E.g. We will assume input is correct (explaining why there is no validation)

### Requirements

- List of conditions to be met for the feature
- E.g. Every column/row must display a value, i.e. cannot be empty

### Limitations

- A list of things this work will specifically not do
- E.g. This feature will only handle the most frequent use case X

### Affected/Changed Components

- Files
- Environment variables
- External executables
- Database tables
- Cron job settings
- Etc.

#### GUI Change description

Describe changes the user will see.

#### Code Change Description *(Pseudocode optional)*

Describe code changes planned for the feature.

#### Tests

A test should be planned for each requirement (above), where possible.

### LINKED ISSUE #398: Update FCirc output format to accommodate data with multiple tracer compounds per animal
### Feature Inspiration

Since Ra/Rd (FCirc) is dependent on the serum measurement of the tracer compound, experiments that use tracers with multiple labels will have multiple Ra/Rd values per serum sample, one for each tracer compound. This requires an update to the output table, which right now only displays one set of values per serum sample.

### Feature Description

- Fcirc reports values for each tracer compound as additional rows.

Recommendation from @mneinast, described in these [google drive slides](https://docs.google.com/presentation/d/1US08FxF7_hOIkqcKyRkYtLrZs1ZllsJ4MDsfdAd5Zck/edit?usp=sharing)

### Comment

-----

### Assumptions

- List of assumptions made WRT the code
- E.g. We will assume input is correct (explaining why there is no validation)

### Requirements

- List of conditions to be met for the feature
- E.g. Every column/row must display a value, i.e. cannot be empty

### Limitations

- A list of things this work will specifically not do
- E.g. This feature will only handle the most frequent use case X

### Affected/Changed Components

- Files
- Environment variables
- External executables
- Database tables
- Cron job settings
- Etc.

#### GUI Change description

Describe changes the user will see.

#### Code Change Description *(Pseudocode optional)*

Describe code changes planned for the feature.

#### Tests

A test should be planned for each requirement (above), where possible.

### PR DESCRIPTION
**Pull request by hepcat72**
## Summary Change Description

Almost everything changed in here relates to changes necessary to make the file validation code and validation database work with the new multi tracer/label related models (infusate, tracer, tracer label, etc.  The maitained model had to change as well because of the previously un-encountered issue of performing maintained field operations on a different database.  When validation failed, the buffered updates had to be flushed and the model managers had to be aware of which database to update.  The managers were changed from plain managers to querysets "as managers" so that `.using(db)` could be applied to them.

## Affected Issue Numbers

- Resolves #395
- Resolves #398

## Code Review Notes

The only substantial portion of these changes that are not related to the theme of this PR are the fcirc, animal_label, and possibly peak_group_label loads in the sample table loader and `.using(db)` changes in the sample table loader code (which is also in a separate PR).

I turned off the CI tests for this PR.  These changes are just copies of files from the fcirc_multi branch dropped into a new branch off the `infusate_label` branch (the starting point of the master branch for this effort).  I am breaking that code review up into these smaller PRs that are separated by theme.  I am doing it by file simply because it's easier.  If any code here references something you cannot find, just consult to `fcirc_multi` branch/PR.

The PRs I will be submitting are:

- `fcirc_multi_models`
- `fcirc_multi_format`
- `fcirc_multi_validation` (this PR)
- `fcirc_multi_pagination`
- `fcirc_multi_tests`
- `fcirc_multi_minor` (comments/renames/etc)

## Checklist

These are the checks for the overall change set...

- [x] All issue requirements satisfied (or no linked issues)
- [x] [Linting passes](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#linting).
- [x] [Migrations created & committed *(or no model changes)*](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#migration-process)
- Tests
  - [ ] [Tests implemented *(or no code changes)*](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#test-implementation)
  - [x] [All *multi_working* tag tests pass locally](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#quality-control)
  - [x] All example load tests pass (remotely) *(or their failures predated and are unrelated to this branch)*
  - [x] `@tag("multi_working")` added to newly passing test functions/classes *(or no newly passing tests)*
  - [x] `@tag("multi_broken")`, `@tag("multi_unknown")`, or `@tag("multi_mixed")` removed from newly passing test functions/classes *(or no newly passing tests)*

### CODE REVIEW

**Review by lparsons — APPROVED** [review]
Looks good from what I can tell.

**Review by fkang-pu — APPROVED** [review]
As long as tests pass, I have no concern about the changes.

**Review by jcmatese — APPROVED** [review]
Fine by me! [though I would prefer eventually swapping the multiple databases paradigm]

**Comment by hepcat72** [comment]
> Fine by me! [though I would prefer eventually swapping the multiple databases paradigm]

Yeah, I would prefer that as well.  Unfortunately, validation of the accucor files requires that the sample table already be loaded.  Perhaps we should have an issue to implement validation without the sample load being necessary? Is that something you'd be interested in tackling?

The other reason is that running the accucor load in debug mode has database side-effects (#357), so even if we worked out how to do the accucor validation without loading the sample table, validating still isn't cleanly possible yet either.

**Comment by hepcat72** [comment]
Defering merge to #493

**Pull request closed without merging**
